version: '3.7'

services:
  react:
    container_name: octo-cntr
    image: octo-img
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
#    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
#      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    tty: true